apiVersion: v1
description: Scriptable and transparent HTTP(S) proxy using mitmproxy
name: tproxy
version: 0.0.1
appVersion: 2.0.2
home: https://mitmproxy.org
sources:
- https://github.com/mitmproxy/mitmproxy
- https://github.com/MatsNL/kubernetes-tproxy
icon: https://secure.gravatar.com/avatar/eed3539f6ce40c5b398509995daf6555.jpg?s=512&r=g&d=mm
#maintainers:
#- name: MatsNL
#  email: 