images:
  tproxy_registry: docker.io/mpenelissen
  pullPolicy: IfNotPresent
  mitmproxy: mitmproxy/mitmproxy:2.0.2
  tproxy_initializer: tproxy-initializer:0.1.0
  tproxy_podwatch: tproxy-podwatch:0.1.0
  tproxy_sidecar: tproxy-sidecar:0.1.0

tproxy:
  useRBAC: false
  useInitializer: false
  hostPort: 8080
  addStandardModeProxy: false
  # blockSvcCIDR: 10.11.240.0/20
  # allowDNS: 10.11.240.10
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi